trigger:
- master

resources:
- repo: self
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Test_trivy
  displayName: 'Trivy test'
  pool:
      name: Default
  jobs:
  - job: Test_with_trivy
    steps:
    - task: trivy@1
      inputs:
        version: 'latest'
        path: '.'
- stage:  Build
  displayName: Build new img
  pool:
      name: Default
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'my_dockerHub'
        repository: 'gandi'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        arguments: '-t bogdanioanliviu/gandi:$(Build.BuildId)'
    - task: Docker@2
      inputs:
        containerRegistry: 'my_dockerHub'
        repository: 'bogdanioanliviu/gandi'
        command: 'push'
        tags: '$(Build.BuildId)'
